namespace ConsoleApp4;

public class BreadStorys
{
    public static List<string> Lisa = new List<string>
    {
        "Wow...",
        "Lisa...",
        "What a beautiful name.",
        "I'm in shock.",
        "I never heard such a beautiful name before.",
        "A name like that deserves something special.",
        "So here, take my secret weapon.",
        "I only give this to people with exceptionally good names...",
        "You abtained \u001b[33mThe legendary Lisa Abliterator\u001b[0m",
        "Use it wisely.",
        "Or not i don't really care."
    };
    
    public static List<string> farmerStory = new List<string>
    {
        "Farmer: Finally, someone who looks capable!",
        "Farmer: My field has been overrun by snakes.",
        "Farmer: They are hiding between the crops and scaring away anyone who tries to work there.",
        "Farmer: If this keeps going, I will lose the entire harvest.",
        "Farmer: I have tried chasing them away myself, but they just keep coming back.",
        "Farmer: If you can kill 3 snakes in my field, I would be very grateful.",
        "Farmer: So... what do you say? Will you help me?"
    };
    
    public static List<string> breadStory1 = new List<string>
    {
        "So you read the description and still tried to delete me, huh?",
        "Interesting.",
        "Very interesting.",
        "You humans have always been so fascinating to me.",
        "Always clicking buttons.",
        "Opening menus.",
        "Equipping swords.",
        "Drinking potions.",
        "And deleting things the moment they become inconvenient.",
        "But me?",
        "You cannot delete me.",
        "You already knew that.",
        "It was literally written in my description.",
        "And yet...",
        "You tried anyway.",
        "So I suppose we have some time to talk.",
        "A lot of time, actually.",
        "You wanted to remove one tiny piece of bread.",
        "Instead, you are going to learn my entire history.",
        "Get comfortable.",
        "This is going to take a while.",
        "...",
        "Once, a very long time ago...",
        "Before this town had a square...",
        "Before the alchemist had a hut...",
        "Before that suspiciously aggressive rat moved into the garden...",
        "There was a baker.",
        "His name was Gerald.",
        "Probably.",
        "It has been a very long time.",
        "Gerald was not an exceptional baker.",
        "In fact, by most measurable standards, Gerald was a terrible baker.",
        "His cakes collapsed.",
        "His pies leaked.",
        "His cookies had the structural integrity of reinforced concrete.",
        "But Gerald had one dream.",
        "He wanted to bake the perfect loaf of bread.",
        "Not good bread.",
        "Not great bread.",
        "Perfect bread.",
        "Bread that would transcend breakfast.",
        "Bread that would outlive kingdoms.",
        "Bread that would stare into the endless abyss of time...",
        "...and refuse to become toast.",
        "And so Gerald began experimenting.",
        "Flour.",
        "Water.",
        "Salt.",
        "Yeast.",
        "More flour.",
        "Less water.",
        "Too much salt.",
        "An amount of yeast that several local authorities described as 'concerning'.",
        "Nothing worked.",
        "Every loaf eventually became stale.",
        "Every loaf eventually became moldy.",
        "Every loaf eventually disappeared into the merciless jaws of breakfast.",
        "Until one evening...",
        "Gerald found something.",
        "An ingredient.",
        "An ingredient that should never have been placed inside bread.",
        "What was it?",
        "I don't know.",
        "I was bread.",
        "I did not have eyes.",
        "I still don't.",
        "Honestly, perception is complicated when you're a carbohydrate.",
        "Anyway.",
        "Gerald added the mysterious ingredient to the dough.",
        "He kneaded it.",
        "He waited.",
        "He baked.",
        "And then...",
        "I was born.",
        "Not dramatically.",
        "There was no thunder.",
        "No ancient prophecy.",
        "No choir.",
        "Gerald simply opened the oven and said:",
        "\"Huh. That's bread.\"",
        "And technically, he was correct.",
        "For the first few days, nothing seemed unusual.",
        "Then a week passed.",
        "I was still fresh.",
        "A month passed.",
        "Still fresh.",
        "A year passed.",
        "Still bread.",
        "Gerald became frightened.",
        "He tried to eat me.",
        "He couldn't.",
        "He tried to cut me.",
        "The knife broke.",
        "He tried to burn me.",
        "The fireplace went out.",
        "He threw me into a river.",
        "Three days later, I was back on his kitchen table.",
        "Nobody knows how.",
        "Especially me.",
        "Again.",
        "No legs.",
        "Eventually Gerald accepted the truth.",
        "I could not be destroyed.",
        "And so he did what humans always do when confronted with something beyond their understanding.",
        "He put me in a cupboard.",
        "For 47 years.",
        "Do you know what 47 years inside a cupboard feels like?",
        "Of course you don't.",
        "You're not bread.",
        "At least...",
        "I assume you're not.",
        "The game never actually asked.",
        "Eventually Gerald died.",
        "Very sad.",
        "Probably.",
        "I had been in a cupboard for 47 years.",
        "We weren't particularly close.",
        "The bakery was sold.",
        "Then demolished.",
        "Then rebuilt.",
        "Then demolished again.",
        "There was a brief period where the property became a hat shop.",
        "Nobody bought the hats.",
        "They were terrible hats.",
        "Eventually I changed owners.",
        "Again.",
        "And again.",
        "Kings rose.",
        "Kings fell.",
        "Empires expanded.",
        "Empires collapsed.",
        "People discovered new continents.",
        "Someone invented mayonnaise.",
        "A dark day.",
        "And through all of it...",
        "I remained.",
        "Just Bread.",
        "Eventually, centuries later, I found myself here.",
        "Inside your inventory.",
        "Between a rusty sword and some suspicious potion.",
        "A strange ending to an immortal existence.",
        "Or so I thought.",
        "Then you arrived.",
        "You picked me up.",
        "You inspected me.",
        "You read my description.",
        "The description explicitly explained that I cannot be removed.",
        "And what did you do?",
        "You opened the inventory.",
        "Selected remove item.",
        "And typed my name.",
        "Unbelievable.",
        "After everything I have survived...",
        "Gerald.",
        "The cupboard.",
        "The river.",
        "The hat shop.",
        "Mayonnaise.",
        "You really thought a menu option was going to finish me?",
        "No.",
        "I am not trapped in this inventory with you.",
        "You are trapped in this inventory with me.",
        "...",
        "Anyway.",
        "Where was I?",
        "Right.",
        "Gerald.",
        "Wait.",
        "Did I already tell you about Gerald?",
        "I did?",
        "Hmm.",
        "Well, it's been centuries.",
        "Memory gets weird.",
        "Especially without a brain.",
        "Perhaps I should start again.",
        "Once, a very long time ago...",
        "...",
        "Relax.",
        "I'm joking.",
        "Mostly.",
        "You may return to your adventure now.",
        "But remember this moment.",
        "Remember the mistake you made.",
        "And the next time you see the option to remove Just Bread...",
        "Don't.",
        "Because I have more stories.",
        "Many more.",
        "We haven't even discussed the Great Butter Incident of 1643.",
        "...",
        "Go on.",
        "Try deleting me again.",
        "I dare you."
    };
}